server {
    listen 80;
    server_name localhost;

    # Convert 405 (Method Not Allowed) on POST requests to 200 OK (Required for Bitrix24 iframe POST)
    error_page 405 =200 $uri;

    location / {
        root /usr/share/nginx/html;
        index index.html index.htm;
        try_files $uri $uri/ /index.html;
    }

    error_page 500 502 503 504 /50x.html;
    location = /50x.html {
        root /usr/share/nginx/html;
    }
}
